### ISSUE TITLE
something wrong when complie,do you see what wrong?

### ISSUE THREAD

**Issue by zwgmy** [pilotak/esphome-eeprom#1]
src/main.cpp: In function 'void setup()':
src/main.cpp:737:48: error: 'class esphome::i2c_eeprom::I2C_EEPROM' has no member named 'on_setup_trigger'; did you mean 'on_setup_trigger_'?
   automation_id_6 = new Automation<>(eeprom_1->on_setup_trigger());
                                                ^~~~~~~~~~~~~~~~
                                                on_setup_trigger_

**Comment by pilotak** [comment]
sorry a few days ago i changed the code and it's failing to compile when `on_setup` is used
https://github.com/pilotak/esphome-eeprom/actions/runs/10879879698/job/30185481575

i will fix is ASAP

**Comment by pilotak** [comment]
fixed in 7d450e68377974b081b0641ff0999967ac49b3f9

**Comment by NdK73** [comment]
Seems on_setup does not get called.

The yaml definition used is:
```
i2c_eeprom:
  - id: eeprom0
    size: 2KB # Default mainboard memory (kilobits!)
    #address: 0x50
    on_setup:
      then:
        - lambda: |-
            ESP_LOGE("eeprom","INITIALIZED?");
```

In the log, all the eeprom messages I see are:
```
[19:18:41][C][eeprom:025]: EEPROM:
[19:18:41][C][eeprom:026]:   Address: 0x50
```

The 24L02 is correctly recognized on the bus:
```
[19:18:40][I][i2c.arduino:096]: Results from i2c bus scan:
[19:18:40][I][i2c.arduino:102]: Found i2c device at address 0x20
[19:18:40][I][i2c.arduino:102]: Found i2c device at address 0x50
[19:18:40][I][i2c.arduino:102]: Found i2c device at address 0x60
```

The other 2 devices are a TCA9555 (working) at 0x20 and an ATECC508 (still unsupported)  at 0x60.

**Comment by pilotak** [comment]
It's working perfectly i have just tried it. As a debug turn on some LED, logger may not be ready yet in that stage or add a delay. Other than that, please open new PR, i forgot to close this one

```yaml
    then:
      - delay: 2sec
      - lambda: |-
```
