### ISSUE TITLE
Size in in KiloBITs, not kiloBYTES?

### ISSUE THREAD

**Issue by NdK73** [pilotak/esphome-eeprom#3]
Hi.

IIUC, the "size:" config is meant to give the memory size in kilobits, but uses "KB" that usually stands for kilobytes.
So a 24L02 is 2kb=256B, while a 24L04 is 4kb=512B.

**Comment by pilotak** [comment]
i realise this is confusing, i tried to keep the enum in upper case as this is a good practice

https://github.com/pilotak/esphome-eeprom/blob/df01f483148c84166c7dc418dfc44fbfb6f54b0e/components/i2c_eeprom/__init__.py#L11-L22

looking at the datasheets of different EEPROMs, they only specify "K" ie 256K, 2K so maybe i should change it to that?

**Comment by NdK73** [comment]
That would be better since it would match docs. Or use the 'extended' 2KBITS. Or even a way simpler change in the docs:

> * **size** - (required) Set the EEPPROM size (**in bits**, not bytes): 1KB, 2KB, 4KB, 8KB, 16KB, 32KB, 64KB, 128KB, 256KB, 512KB

**Comment by pilotak** [comment]
done a5b7c15b3a7c53fa1d9ea9ff99ca6225f1a23f40 

thank you for feedback
